version: "3.9"
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - 8080:8080
    expose:
      - 8080
  db:
    image: mysql:8.3.0
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - database:/var/lib/mysql
    expose:
      - 3306
volumes:
  database:
